/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 * Reference manual address:
 * https://www.st.com/resource/en/reference_manual/dm00031020-stm32f405-415-stm32f407-417-stm32f427-437-and-stm32f429-439-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf
 */

#include <stdint.h>
#include <stdio.h>

/* Global variables */
int g_data1 = -4000;
int g_data2 = 200;
int result = 0;

/*
 * Main memory block base address. Information can be found in reference manual, p. 75
 * Sector 0 start address: 0x0800 0000
 * Sector 11 end address: 0x080F FFFF
 * When we download our code, it will start from sector 0 start address, onwards.
 * We can look at the memory locations in the memory Browser (Windows > Show View > Memory Browser)
 *
 * Data memory is in the SRAM - the STM32F407 has SRAM1 and SRAM2. SRAM1 is the main SRAM block and
 * is 112KB. SRAM2 is 16KB.
 * SRAM1 and SRAM2 mapped at address 0x2000 0000 and accessible by all AHB masters
 *
 */


int main(void)
{
	result = g_data1 + g_data2;
	printf("Result = %d\n", result);

    /* Loop forever */
	for(;;);
}
